import { ImageSourcePropType } from 'react-native';

interface Images {
  icon_logo: ImageSourcePropType;
  icon_onboarding_image_one: ImageSourcePropType;
  icon_onboarding_image_two: ImageSourcePropType;
  icon_onboarding_image_three: ImageSourcePropType;
  icon_back_press_arrow: ImageSourcePropType;
  icon_email_black: ImageSourcePropType;
  icon_lock_black: ImageSourcePropType;
  icon_eye_open_black: ImageSourcePropType;
  icon_eye_close_black: ImageSourcePropType;
  icon_google_logo: ImageSourcePropType;
  icon_facebook_logo: ImageSourcePropType;
  icon_person_black: ImageSourcePropType;
  icon_home: ImageSourcePropType;
  icon_profile: ImageSourcePropType;
  icon_my_needs: ImageSourcePropType;
  icon_my_response: ImageSourcePropType;
  icon_plus_bottom_tab: ImageSourcePropType;
  icon_down_arrow_black: ImageSourcePropType;
  icon_checked_box_green: ImageSourcePropType;
  icon_unhecked_box_black: ImageSourcePropType;
  icon_membership_star_green: ImageSourcePropType;
  icon_arrow_right_black: ImageSourcePropType;
  icon_add_black: ImageSourcePropType;
  icon_card_black: ImageSourcePropType;
  icon_succes_green: ImageSourcePropType;
  icon_booking_selected: ImageSourcePropType;
  icon_booking_unselected: ImageSourcePropType;
  icon_message_selected: ImageSourcePropType;
  icon_message_unselected: ImageSourcePropType;
  icon_profile_unselected: ImageSourcePropType;
  icon_profile_selected: ImageSourcePropType;
  icon_notification_black: ImageSourcePropType;
  icon_check_green: ImageSourcePropType;
  icon_setting_black: ImageSourcePropType;
  icon_info_circle_black: ImageSourcePropType;
  icon_profile_place_holder: ImageSourcePropType;
  icon_logout_red: ImageSourcePropType;
  icon_calendar: ImageSourcePropType;
  icon_clock: ImageSourcePropType;
  icon_send_message: ImageSourcePropType;
  icon_sorting_listing_image: ImageSourcePropType;
  icon_clock_green: ImageSourcePropType;
  icon_call_black: ImageSourcePropType;
  icon_map_black: ImageSourcePropType;
  icon_star_yellow: ImageSourcePropType;
  icon_global_black: ImageSourcePropType;
}

const images: Images = {
  icon_logo: require('./icon_logo.png'),
  icon_onboarding_image_one: require('./icon_onboarding_image_one.png'),
  icon_onboarding_image_two: require('./icon_onboarding_image_two.png'),
  icon_onboarding_image_three: require('./icon_onboarding_image_three.png'),
  icon_back_press_arrow: require('./icon_back_press_arrow.png'),
  icon_email_black: require('./icon_email_black.png'),
  icon_lock_black: require('./icon_lock_black.png'),
  icon_eye_open_black: require('./icon_eye_open_black.png'),
  icon_eye_close_black: require('./icon_eye_close_black.png'),
  icon_google_logo: require('./icon_google_logo.png'),
  icon_facebook_logo: require('./icon_facebook_logo.png'),
  icon_person_black: require('./icon_person_black.png'),
  icon_home: require('./icon_logo.png'),
  icon_profile: require('./icon_person_black.png'),
  icon_my_needs: require('./icon_email_black.png'),
  icon_my_response: require('./icon_back_press_arrow.png'),
  icon_plus_bottom_tab: require('./icon_logo.png'),
  icon_down_arrow_black: require('./icon_down_arrow_black.png'),
  icon_checked_box_green: require('./icon_checked_box_green.png'),
  icon_unhecked_box_black: require('./icon_unhecked_box_black.png'),
  icon_membership_star_green: require('./icon_membership_star_green.png'),
  icon_arrow_right_black: require('./icon_arrow_right_black.png'),
  icon_add_black: require('./icon_add_black.png'),
  icon_card_black: require('./icon_card_black.png'),
  icon_succes_green: require('./icon_succes_green.png'),
  icon_booking_selected: require('./icon_booking_selected.png'),
  icon_booking_unselected: require('./icon_booking_unselected.png'),
  icon_message_selected: require('./icon_message_selected.png'),
  icon_message_unselected: require('./icon_message_unselected.png'),
  icon_profile_unselected: require('./icon_profile_unselected.png'),
  icon_profile_selected: require('./icon_profile_selected.png'),
  icon_notification_black: require('./icon_notification_black.png'),
  icon_check_green: require('./icon_check_green.png'),
  icon_setting_black: require('./icon_setting_black.png'),
  icon_info_circle_black: require('./icon_info_circle_black.png'),
  icon_profile_place_holder: require('./icon_profile_place_holder.png'),
  icon_logout_red: require('./icon_logout_red.png'),
  icon_calendar: require('./icon_profile_place_holder.png'),
  icon_clock: require('./icon_profile_place_holder.png'),
  icon_send_message: require('./icon_send_message.png'),
  icon_sorting_listing_image: require('./icon_sorting_listing_image.png'),
  icon_clock_green: require('./icon_clock_green.png'),
  icon_call_black: require('./icon_call_black.png'),
  icon_map_black: require('./icon_map_black.png'),
  icon_star_yellow: require('./icon_star_yellow.png'),
  icon_global_black: require('./icon_global_black.png'),
};
export default images;
